---
- hosts: localhost
  name: Volume Action
  vars:
    hostname: seatsnetapp01.alaskaair.com
    username: YYYYYYYYYYY
    password: XXXXXXXXXXXXXX
    vserver: seatssan01
    aggr: aggr1_sas_seatsnetapp01_01
    vol_name: ansibleVol
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      policy: default
      #junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
